version: 0.2
phases:
install:
commands:
      - echo Installing python 3.6...
      - yum -y groupinstall development
      - yum -y install zlib-devel
      - wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
      - tar xJf Python-3.6.0.tar.xz
      - cd Python-3.6.0
      - ./configure
      - make
      - make install 
pre_build:
commands:
- echo Installing dependencies...
- python3 -V
- yarn install
build:
commands:
- echo Building...
- yarn build
artifacts:
files:
- "**/*"
discard-paths: no
base-directory: dist